export const MAX_FILE_SIZE_BYTES = 300 * 1024 * 1024 // 300MB, mirrors storage.rules
export const STORAGE_FOLDER = 'uploads'
export const THUMBNAIL_STORAGE_FOLDER = 'uploads/thumbs'
export const MEDIA_COLLECTION = 'media'
export const MAX_PHOTO_ITEMS = 1000
export const MAX_VIDEO_ITEMS = 50
export const MAX_GALLERY_ITEMS = MAX_PHOTO_ITEMS + MAX_VIDEO_ITEMS
export const GALLERY_PAGE_SIZE = 30
export const UPLOADER_NAME_STORAGE_KEY = 'wedding-uploader-name'
